### ISSUE TITLE
revisit the IT tests 

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/skeleton-starter-flow-cdi#413]
the build for the v23 branch is always failing. 

the IT tests and its setup need to be revisited and corrected. 

https://teamcity.vaadin.com/viewType.html?buildTypeId=Flow_FlowStarters_FlowCdiStarter_2&tab=buildTypeHistoryList

**Comment by mcollovati** [comment]
@ZheSun88, is this issue still valid?

**Comment by ZheSun88** [comment]
locally it passes for me.
let us make a PR to the v23 branch to see. (the previous validation build doesn't run the correct IT profile)

**Comment by ZheSun88** [comment]
yes, it is still needed.. check here https://teamcity.vaadin.com/buildConfiguration/Flow_FlowStarters_FlowCdiStarter_2/142682?
