### ISSUE TITLE
demo is not running with JDK>8

### ISSUE THREAD

**Issue by svenruppert** [vaadin/skeleton-starter-flow-cdi#72]
mvn clean install will lead to 

[WARNING] Error injecting: org.apache.maven.plugin.failsafe.IntegrationTestMojo
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

**Comment by mehdi-vaadin** [comment]
Which version of Java are you using? I tried it with Java 11 and didn't see this warning.

**Comment by denis-anisimov** [comment]
We need JDK 11 profile as e.g. for beverage starter or here: https://github.com/vaadin/skeleton-starter-flow/blob/master/pom.xml#L197
